apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-induce
  labels:
    app: stress-maker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-maker
  template:
    metadata:
      labels:
        app: stress-maker
    spec:
      containers:
      - name: memory-stress-ctr
        image: polinux/stress
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            cpu: "100m"
            memory: "256Mi"
        command: ["stress"]
        args: ["-v", "--vm", "1", "--vm-bytes", "50M", "--vm-hang", "4"]
      - name: cpu-stress-ctr
        image: vish/stress
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            cpu: "100m"
            memory: "100Mi"
        args:
        - -cpus
        - "1"
