{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "zee5.fullname" . }}-{{ .Values.version }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "zee5.fullname" . }}-{{ .Values.version }}
  minReplicas: {{ .Values.autoscaling.minReplicas_v1 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas_v1 }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage}}
{{- end }}
---
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "zee5.fullname" . }}-{{ .Values.version2 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "zee5.fullname" . }}-{{ .Values.version2 }}
  minReplicas: {{ .Values.autoscaling.minReplicas_v2 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas_v2 }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage}}
{{- end }}
