apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: {{ .Values.namespace }}-custome-istio-ingress-gw
spec:
  profile: empty
  components:
    ingressGateways:
      - namespace: {{ .Values.namespace }}
        name: {{ .Values.namespace }}-ingress-gateway
        enabled: true
        label:
          istio: {{ .Values.namespace }}-internal-ingressgateway
        k8s:
           service:
              type: NodePort
           hpaSpec:
                maxReplicas: 300
                minReplicas: 1
                metrics:
                  -  resource:
                        name: cpu
                        target:
                          averageUtilization: 40
                          type: Utilization 
                     type: Resource
                scaleTargetRef:  
                    apiVersion: apps/v1
                    kind: Deployment
                    name: {{ .Values.namespace }}-ingress-gateway
