apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.ingress.name }}-ingress-gw
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: {{ .Values.namespace }}-internal-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.ingress.name }}-ingress-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.ingress.name }}-ingress-gw
  http:
   - match:
     - headers:
        version:
            exact: v1
       uri:
         prefix: "/{{ .Values.prob }}"
     route:
      - destination:
          port:
            number: 8080 # can be omitted if it's the only port for reviews
          host: {{ include "zee5.fullname" . }}-service.{{ .Values.namespace }}.svc.cluster.local
          subset: {{ .Values.version1 }}
     retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx  
   - match:
     - headers:
        version:
            exact: v2
       uri:
         prefix: "/{{ .Values.prob }}"
     route:
      - destination:
          port:
            number: 8080 # can be omitted if it's the only port for reviews
          host: {{ include "zee5.fullname" . }}-service.{{ .Values.namespace }}.svc.cluster.local
          subset: {{ .Values.version2 }}
     retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx    
   - match:
     - uri:
         prefix: /{{ .Values.prob }}
     route:
      - destination:
          port:
            number: 8080 # can be omitted if it's the only port for reviews
          host: {{ include "zee5.fullname" . }}-service.{{ .Values.namespace }}.svc.cluster.local
          subset: {{ .Values.version }}
        weight: {{ .Values.weight1 }}
      - destination:
          port:
            number: 8080 # can be omitted if it's the only port for reviews
          host: {{ include "zee5.fullname" . }}-service.{{ .Values.namespace }}.svc.cluster.local
          subset: {{ .Values.version2 }}
        weight: {{ .Values.weight2 }}    
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.ingress.name }}-dr
spec:
  host: {{ include "zee5.fullname" . }}-service.{{ .Values.namespace }}.svc.cluster.local
  subsets:
  - name: {{ .Values.version }}
    labels:
      version: {{ .Values.version }}
  - name: {{ .Values.version2 }}
    labels:
      version: {{ .Values.version2 }}
     
        
