apiVersion: v1
kind: Service
metadata:
  name: {{ include "zee5.fullname" . }}-service
  labels:
    {{- include "zee5.labels" . | nindent 4 }}
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: {{ .Values.service.type }}
  ports:
     - protocol: TCP
       port: 8080
       targetPort: {{ .Values.port }}
       name: http-{{ .Values.containername }}
  selector:
    {{- include "zee5.selectorLabels" . | nindent 4 }}
    app: {{ .Values.app }}
