# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: {{ .Values.guestbookUI.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.guestbookUI.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: {{ .Values.guestbookUI.deployment.image.repository }}:{{ .Values.guestbookUI.deployment.image.tag }}
        name: guestbook-ui
        resources:
          requests:
            cpu: {{ .Values.guestbookUI.deployment.resources.requests.cpu }}
            memory: {{ .Values.guestbookUI.deployment.resources.requests.memory }}
        ports:
        - containerPort: {{ .Values.guestbookUI.deployment.port }}

