# templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: {{ .Values.guestbookUI.service.port }}
    targetPort: {{ .Values.guestbookUI.service.targetPort }}
  selector:
    app: guestbook-ui

